services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: tgdata
      POSTGRES_PASSWORD: tgdata
      POSTGRES_DB: tgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
