"""initial

Revision ID: 2027ac7f3df1
Revises: 
Create Date: 2026-08-19 15:25:11.116552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2027ac7f3df1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('channel', 'comment_chat', 'group', name='sourcekind'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('linked_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('inactive_reason', sa.Enum('no_access', 'disabled_by_user', name='inactivereason'), nullable=True),
    sa.ForeignKeyConstraint(['linked_channel_id'], ['sources.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tg_msg_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reply_to_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_top_id', sa.BigInteger(), nullable=True),
    sa.Column('grouped_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('fwd_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'tg_msg_id')
    )
    op.create_table('sync_state',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('oldest_processed_id', sa.BigInteger(), nullable=True),
    sa.Column('newest_processed_id', sa.BigInteger(), nullable=True),
    sa.Column('backfill_done', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('thread_roots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('root_msg_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_source_id', sa.Integer(), nullable=False),
    sa.Column('channel_msg_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'root_msg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_roots')
    op.drop_table('sync_state')
    op.drop_table('messages')
    op.drop_table('sources')
    # ### end Alembic commands ###
